# This is a basic workflow to help you get started with Actions

name: Postman CI with API on Docker

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: run Docker image with GAD application
        run: docker run -p 3000:3000 -d jaktestowac/gad
        
      - uses: actions/setup-node@v3
        with:
          node-version: 'latest'
          
      - name: Install Newman CLI
        run: npm install -g newman
      - name: Install Newman HTML reporter
        run: npm install -g newman-reporter-htmlextra
      - name: Make the test script files executable
        run: chmod +x ./.github/workflows/run_all_tests_in_newman.sh
        
      - name: Run tests
        run: ./.github/workflows/run_all_tests_in_newman.sh
        continue-on-error: true
        
      - name: Upload newman html report
        uses: actions/upload-artifact@v3
        with:
          name: newman_html_reports
          path: newman
